export default {
	return_to_homepage: 'Return To Homepage',
	languages: 'Languages',
	privacy_policy: 'Privacy Policy',
	contact_us: 'Contact Us',
	enterprise_user: 'Enterprise User',
	save_the_environment: 'Save the environment',
	monitor_checking: 'Monitor Checking',
	hk_only: '3HK only',
	e_degree_mobile_cash_recycling: 'etrade - Cash Second-hand Phone Trade',
	collection_steps: 'Collection Steps',
	get_a_quote: 'Get a Quote',
	skip: 'Skip',
	get_a_trade_in_estimate: 'Get a trade-in estimate',
	answer_a_few_questions: 'Answer a few questions',
	back: 'Back',
	next: 'Next',
	previous: 'Previous',
	submit: 'Submit',
	quoted_value: 'Quoted Value',
	pick_up_service: 'Pick-up Service',
	drop_off_at_3_shop: 'Drop-off at 3 Shop',
	start_over: 'Start Over',
	transaction_during_face_to_face_trading: 'Transaction during face-to-face trading',
	transaction_within_three_working_days: 'Transaction within three working days',
	support_bank_transfer_fps_and_alipay_hk: 'Support bank transfer,FPS and Alipay HK',
	not_record: 'No data available at the moment',
	loading: 'Loading',
	fail: 'Fail',
	success: 'Success',
	request_fail: 'Request Fail',
	please_enter_the_reference_number: 'Please enter the reference number',
	please_enter_the_sms_verification_code: 'Please enter the SMS verification code',
	what_is_your_phone_number: 'What is your phone number',
	verification_code: 'Verification code',
	retrieve_again: 'Retrieve again',
	second: ' second ',
	get_code: 'Get Code',
	obtaining_verification_code: 'Obtaining verification code',
	send_after_the_countdown_is_over: 'Send after the countdown is over',
	verification_code_has_been_sent: 'Verification code has been sent',
	confirm: 'Confirm',
	please_enter_your_phone_number: 'Please enter your phone number',
	scan: 'Scan',
	please_scan_within_the_store: 'Please scan within the store',
	check_your_model_now: 'Check Your Model Now',
	new_mobile_phone_transfer_strategy: 'New mobile Phone transfer strategy',
	why_choose_e_trade: 'Why choose e trade',
	registration_completed_ur_staff_will_contact_you_shortly: 'Registration completed. Our staff will contact you shortly.',
	your_order_number: 'Your order number: ',
	copy: 'Copy',
	copy_success: 'Copy Success',
	copy_fail: 'Copy Fail',
	submit_success: 'Submit Success',
	invaluable: 'Invaluable',
	payment: 'Payment',
	tip_1: 'Please fill in the contact information and we will arrange the pucj-up.',
	tip_2: 'Please fill in the contact details and drop-off shop.',
	please_fill_in_your_name: 'Please fill in your name',
	please_provide_your_contact_phone_number: 'Please provide your contact phone number',
	tip_3: 'Contact phone number is 8-digits HK number only',
	please_fill_in_the_address: 'Please fill in the address',
	please_select_region: 'Please select district',
	tip_4: 'The submitted personal information will be discarded after the transaction is completed',
	tip_5: '8-digits HK number only',
	area: 'District',
	address: 'Address',
	remark: 'Remarks',
	phone: 'Phone No.',
	name: 'Name',
	nexts: 'Next',
	cancel: 'Cancel',
	bank_name: 'Bank Name',
	account_name: 'Account Name',
	account_number: 'Account Number',
	confirm_account_number: 'Confirm Account Number',
	tip_6: 'Mobile number/ Email address /FPS Identifier',
	tip_7: 'Please enter the Account Number again',
	payee_s_account: "Payee's account",
	payee_s_name: "Payee's Name",
	receipt_qr_code: 'Receipt QR code',
	please_upload_your_receipt_qr_code: 'Please upload your Receipt QR code',
	confirmation: 'Confirmation',
	uploading: 'Uploading',
	tip_8: "Please fill in Payee's account",
	tip_9: "Please fill in Payee's Name",
	tip_10: 'Please upload the payment code',
	tip_11: 'Please fill in Bank Name',
	tip_12: 'Please fill in Account Name',
	tip_13: 'Please fill in Account Number',
	tip_144: 'Please fill in Confirm Account Number',
	tip_155: 'Account Number and Account Number Be Consistent',
	home: 'Home',
	caet_tip1: 'Please fill in the Title',
	caet_tip2: 'Please fill in Last Name',
	caet_tip3: 'Please fill in First Name',
	caet_tip4: 'Please fill in Phone',
	caet_tip5: 'Please fill in the Email',
	caet_tip6: 'Please select a Countries/Region',
	caet_tip7: 'Please select Shipping Area',
	caet_tip8: 'Please fill in the Shipping Address',
	caet_tip9: 'Please select a Countries/Region',
	caet_tip10: 'Please select Billing Area',
	caet_tip11: 'Please fill in the Billing Address',
	caet_tip12: 'Please select Branch',
	select_specs: 'Detail',
	inventory: 'Inventory',
	qty: 'Qty',
	i_ve_chosen_it: "Add to Cart",
	out_of_stock: 'Out of stock',
	insufficient_inventory: 'Insufficient inventory',
	please_select_specs: 'Please select specs',
	cart: 'Cart',
	go_settle: 'Checkout',
	selected_products: 'Selected products',
	clear: 'Clear',
	search: 'Search',
	search_tip1: 'What do you want to buy? Search for it',
	search_tip2: 'Please enter search content',
	please_fill_in: 'Please fill in',
	title: 'Title',
	last_name: 'Last Name',
	first_name: 'First Name',
	phone_1: 'Phone',
	email: 'Email',
	shipping_method: 'Shipping Method',
	country: 'Countries / Region',
	shipping_area: 'Shipping Area',
	shipping_address: 'Shipping Address',
	billing_area: 'Billing Area',
	billing_address: 'Billing Address',
	company_name: 'Company Name',
	customer_remark: 'Customer Remark',
	branch: 'Branch',
	chinese_name: 'Chinese Name',
	same_with_shipping_address: 'Same with Shipping Address',
	freight: 'Freight',
	discount_amount: 'Discount Amount',
	subtotal: 'Subtotal',
	total: 'Total',
	submit_order: 'Submit Order',
	goods: 'Goods',
	confirm_order: 'Confirm order',
	order_detail: 'Order detail',
	order_information: 'Order information',
	order_no: 'Order No.',
	order_time: 'Order Time',
	commodity_information: 'Commodity Information',
	order_amount: 'Order Amount',
	paid_amount: 'Paid Amount',
	continue_shopping: 'Continue Shopping',
	search_order: 'Search Order',
	please_fill_in_the_order_no: 'Please fill in the order No.',
	please_fill_in_the_phone: 'Please fill in the Phone',
	my: 'My',
	additional_information: 'Additional information',
	tip_14: 'Please enter the mobile phone model that needs to be recycled',
	no: 'No',
	yes: 'Yes',
	tip_15: 'Do you have any other mobile phones that need to be collected together?',
	tip_16: 'Please enter a recommendation (if any)',
	tip_17: 'How did you learn about this application?',
	tip_18: 'If you handle mobile trade in services through 3 stores, please enter the purchase order number to obtain contract discounts:',
	search_text: 'Search',
	payment_remark: 'Remark',
	network_connection_unavailable: 'Network connection unavailable',
	product_description: 'Product Description',
	good_detail: 'Good Detail'
}